config/routes.rb
Rails.application.routes.draw do

  root :to => "questions#index"

  resources :questions do
    member do
      post 'upvote'
      post 'downvote'
    end

    # Nested routes
    resources :answers do
      member do
        post 'upvote'
        post 'downvote'
      end
    end
  end

  # Custom routes
  get '/all' => 'questions#index', as: 'all_questions'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :title, :content, :vote, presence: true
  belongs_to :question
  default_scope {
    order("created_at ASC")
  }
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :content, :vote, presence: true
  has_many :answers
  is_impressionable :counter_cache => true, :column_name => :view
  default_scope {
    order("created_at DESC")
  }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :get_question
  before_action :get_answer, only:[:upvote, :downvote]

  def get_question
    @question = Question.find(params[:question_id])
  end

  def get_answer
    @answer = @question.answers.find(params[:id])
  end
####################################################
  def create
    @question.answers.create(answer_params)

    redirect_to question_path(@question)
  end

  def upvote
    @answer.increment!(:vote)

    redirect_to question_path(@question)
  end

  def downvote
    @answer.decrement!(:vote)

    redirect_to question_path(@question)
  end
####################################################
  private

  def answer_params
    params.require(:answer).permit(:title, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @questions = Question.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :get_question, only:[:show, :edit, :update, :destroy, :upvote, :downvote]

  def get_question
    @question = Question.find(params[:id])
  end

  impressionist :actions=>[:show,:index]
#############################################
  def index
    @questions = Question.all
  end

  def show
      @empty = "Sorry, no answer yet!" if @question.answers.count == 0
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)

    redirect_to questions_path
  end

  def update
    @question.update(question_params)

    redirect_to :action => :show, :id => @question
  end

  def destroy
    @question.destroy

    redirect_to questions_path
  end

  def upvote
    @question.increment!(:vote)

    # respond_to do |format|
    #   # format.html
    #   format.js
    #   format.json {render json: @question}
    # end
    # render json: @question

    redirect_to questions_path
  end

  def downvote
    @question.decrement!(:vote)

    # render json: @question

    redirect_to questions_path
  end
#############################################
  private

  def question_params
    params.require(:question).permit(:title, :content)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/answers/_answer.html.erb
<!-- (1) Rendering Partial Collections

The partial here will be rendered once for EACH answer that is in the @question.answers collection.

As the render method iterates over the @question.answers collection, it assigns each answer to a local variable named the same as the partial, i.e. answer -->
<div class="a_votes">
  <%= answer.vote %> <br>
  votes
</div>
<div class="answer_voting">
  <p><%= link_to "Up", upvote_question_answer_path(@question, answer), method: :post %></p>
  <p><%= link_to "Down", downvote_question_answer_path(@question, answer), method: :post %></p>
</div>
<div class="answer_content">
  <h3><%= answer.title %></h3>
  <p><%= answer.content %></p>
</div>
<p class="divisor"></p>

app/views/answers/_form.html.erb
<!-- (2) Rendering a Partial Form

This partial template (answers/form) is defined by the render in controller.

Rails is smart enough to spot the forward slash in the string and realize that you want to render the _form.html.erb -->
<div id="create_answer">
  <%= form_for [@question, @question.answers.build], html: {class: "new_form"} do |f| %>
  <fieldset>
    <legend>Answer</legend>
    <ul><li>Please be sure to answer the question. Provide details and share your research!</li></ul>
    <%= f.text_field :title, placeholder: "Title", size: "60" %> <br><br>
    <%= f.text_area :content, placeholder: "What's your answer?", size: "60x10" %> <br>
    <%= f.submit "Post Your Question", data: {confirm: "Are you sure?"} %>
  </fieldset>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interview Garden</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <!-- <img src="/images/stackoverflow-logo.png" alt="logo" class="logo"> -->
    <h1>Interview<b>Garden</b></h1>
    <h3>Your favorite platform for preparing software engineering interviews.<br><b>Share. Practice. Interview.</b></h3>
  </div>

  <%= yield %>
  <p class="footer_link"><%= link_to 'Back to homepage', questions_path %></p>
  <h3 class="footer">&copy; 2015 Anthony Ng</h3>
</body>
</html>

app/views/questions/edit.html.erb
<%= form_for @question, url: {action: "update"}, html: {class: "edit_form"} do |f| %>
  <fieldset>
    <legend>Title</legend>
    <%= f.text_field :title, placeholder: "What's your programming question? Be specfic.", size: "60" %> <br><br>

    <!-- <h3>Content</h3> -->
    <%= f.label :content, "Details" %> <br>
    <%= f.text_area :content, placeholder: "Details goes here.", size: "60x10" %> <br>
    <%= f.submit "Update Your Question", data: {confirm: "Are you sure?"} %>
  </fieldset>
  <% end %>

<!--
<form accept-charset="UTF-8" action="/articles/create" method="post" class="nifty_form">
  <input id="article_title" name="article[title]" type="text" />
  <textarea id="article_body" name="article[body]" cols="60" rows="12"></textarea>
  <input name="commit" type="submit" value="Create" />
</form>
-->

app/views/questions/index.html.erb
<table class="index_table">
    <tr>
        <th><h2>Recent Interview Questions</h2></th>
        <th><h3><%= link_to "Add Question?", new_question_path %></h3></th>
    </tr>
</table>
<div id="questions_container">
    <% @questions.each do |question| %>
    <div class="single_question" data-question-id="<%= question.id %>">
        <p class="divisor"></p>
        <div class="q_votes">
            <%= question.vote %> <br>
            <div>votes</div>
        </div>
        <div class="status">
            <%= question.answers.size %> <br>
            <div>answers</div>
        </div>
        <div class="views">
            <%= question.view %> <br>
            <div>views</div>
        </div>

        <div class="voting">
            <p><%= link_to "Up", upvote_question_path(question), method: :post %></p>
            <p><%= link_to "Down", downvote_question_path(question), method: :post %></p>
        </div>

        <div class="title">
            <p><%= link_to question.title, question_path(question) %></p>
        </div>
        <div class="created_time">
            <% if (Time.now.to_i - Time.at(question.created_at.to_i).to_i)/(60*60) > 24 %>
                <p>Asked <%= (Time.now.to_i - Time.at(question.created_at.to_i).to_i)/(60*60*24) %> days <%= ((Time.now.to_i - Time.at(question.created_at.to_i).to_i)/(60*60))%24 %> hours ago</p>
            <% else %>
                <p>Asked <%= ((Time.now.to_i - Time.at(question.created_at.to_i).to_i)/(60*60))%24 %> hours ago</p>
            <% end %>
        </div>
    </div>
    <% end %>
</div>

app/views/questions/new.html.erb
<div id="create_question">
  <%= form_for @question, url: {action: "create"}, html: {class: "new_form"} do |f| %>
    <fieldset>
      <legend>Title</legend>
      <%= f.text_field :title, placeholder: "Topic (i.e. Algorithm, Behavioral, Brain Teasers, etc)", size: "60" %> <br><br>

      <!-- <h3>Content</h3> -->
      <%= f.label :content, "Details" %> <br>
      <%= f.text_area :content, placeholder: "What's your programming question? Be specfic.", size: "60x10" %> <br>
      <%= f.submit "Post Your Question", data: {confirm: "Are you sure?"} %>
    </fieldset>
    <% end %>

  <!--
  <form accept-charset="UTF-8" action="/articles/create" method="post" class="nifty_form">
    <input id="article_title" name="article[title]" type="text" />
    <textarea id="article_body" name="article[body]" cols="60" rows="12"></textarea>
    <input name="commit" type="submit" value="Create" />
  </form>
  -->
</div>

app/views/questions/show.html.erb
<div class="single_question">
    <div class="questions">
        <h1><%= @question.title %></h1>
        <p><%= @question.content %></p> <br>
        <table class="show_table">
            <tr>
                <th><h3><%= link_to "Edit", edit_question_path(@question) %></h3></th>
                <th><h3><%= link_to 'Delete', @question, method: :delete, data: {confirm: "Are you sure?"} %></h3></th>
            </tr>
        </table>

    </div>
    <div class="answers">
        <h2><%= @question.answers.size %> Answers</h2>
        <p class="divisor"></p>
        <%= render @question.answers %>
        <h3><%= @empty %></h3>
    </div>

    <div class="your_answer">
        <h2>Your Answer</h2>
        <%= render 'answers/form' %>
    </div>
</div>